name = stock_exchange
description = A stock exchange with dynamic prices, in-game currency, homedecor shop, and skin shop
author = joe7575
version = 0.08
depends = default
optional_depends = homedecor, farming, moreores, wool, dye, tubelib_addons1, building_blocks, sfinv, unified_inventory
